<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_The Da Vinci Code (Robert Langdon)  Op_ae21d8</name>
   <tag></tag>
   <elementGuidId>b65a90d0-c5aa-4fcf-82a8-59412a13f548</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sc-active-c42353a5-03f0-4f2f-a10d-f5eb347ad5af']/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.a-padding-medium > span.a-size-base</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c7a79d08-6952-45d2-adf0-33b0bd134716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-base</value>
      <webElementGuid>2ffa11e8-45e8-4411-8394-af4c3a23ae3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  The Da Vinci Code (Robert Langdon)  Opens in a new tab   was removed from Shopping Cart. </value>
      <webElementGuid>78155f37-3c5d-4ee1-8a69-fc81680e66f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-active-c42353a5-03f0-4f2f-a10d-f5eb347ad5af&quot;)/div[@class=&quot;sc-list-item-removed-msg&quot;]/div[@class=&quot;a-padding-medium&quot;]/span[@class=&quot;a-size-base&quot;]</value>
      <webElementGuid>0dfcf4e7-b3fd-4bea-abe8-f9fb9ab8231e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-active-c42353a5-03f0-4f2f-a10d-f5eb347ad5af']/div/div/span</value>
      <webElementGuid>032278c7-7034-4051-8aa6-129cfd705f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/span</value>
      <webElementGuid>5f6a8e0d-76b6-45dd-abbb-14007447fd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '  The Da Vinci Code (Robert Langdon)  Opens in a new tab   was removed from Shopping Cart. ' or . = '  The Da Vinci Code (Robert Langdon)  Opens in a new tab   was removed from Shopping Cart. ')]</value>
      <webElementGuid>17f44dd3-899a-4b8c-b915-59d240dfb8a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
